### ISSUE TITLE
When would the code be available? 

### ISSUE THREAD

**Issue by drimpossible** [ymcidence/JMLH#1]
Hi!

I am interested in your paper, when will the code be available?

**Comment by ymcidence** [comment]
Hi there

Sorry I was so busy with some other issues previously. This repo will be updated in two weeks.

Thank you
YM

**Comment by AuroMun** [comment]
Any updates?

**Comment by ymcidence** [comment]
> Any updates?

Hi there, this repo is now moved and merged with https://github.com/ymcidence/TBH 

Please check out if you are interested in

**Comment by ymcidence** [comment]
This repo is now moved and merged with our CVPR2020 work https://github.com/ymcidence/TBH

Please have a try. Thank you.
